/*
 * automate.h
 *
 *  Created on: Nov 14, 2024
 *      Author: davidprosperin
 */

#ifndef SRC_AUTOMATE_H_
#define SRC_AUTOMATE_H_

#include <buffer.h>

typedef enum {
     SCAN_FLAG_START1,
     SCAN_FLAG_START2,
     SCAN_RESPONSE_DESCRIPTOR1,
	 SCAN_RESPONSE_DESCRIPTOR2,
	 SCAN_RESPONSE_DESCRIPTOR3,
	 SCAN_RESPONSE_DESCRIPTOR4,
	 SCAN_RESPONSE_DESCRIPTOR5,
     SCAN_QUALITY,
     SCAN_ANGLE_FIRST_PART,
     SCAN_ANGLE_SECOND_PART,
     SCAN_DISTANCE_FIRST_PART,
     SCAN_DISTANCE_SECOND_PART
} state_automate_scan_t;

typedef enum {
     HEALTH_FLAG_START1,
	 HEALTH_FLAG_START2,
	 HEALTH_RESPONSE_DESCRIPTOR1,
	 HEALTH_RESPONSE_DESCRIPTOR2,
	 HEALTH_RESPONSE_DESCRIPTOR3,
	 HEALTH_RESPONSE_DESCRIPTOR4,
	 HEALTH_RESPONSE_DESCRIPTOR5,

	 HEALTH_STATUS,
	 HEALTH_ERROR_CODE0,
	 HEALTH_ERROR_CODE1
} state_automate_health_t;

void automate_scan_decode(uint8_t receivedByte);
void automate_health_decode(uint8_t receivedByte);
#endif /* SRC_AUTOMATE_H_ */
